### ISSUE TITLE
VTU file with 6 point components ?

### ISSUE THREAD

**Issue by oliverstefanov** [mhogg/octree#38]
Great code thanks. I'm trying to read the VTU file but the "points" part contains 6 float components instead of the more usual 3 for each spatial dimension.

What are the last 3 components associated with? Normal vector?

**Comment by mhogg** [comment]
Hi,
I usually open the VTU file with python vtk or Paraview. In am not sure for certain, but I suspect the six values per line just means you have two 3D points per line, not a single 3D point on each line. 
I can look into this a bit further - it would help it you attached your VTU file for me to look at.
Cheers,
Michael

**Comment by oliverstefanov** [comment]
Here is a zip of the octree.vtu file, which is just the result of running your introductory example on the knot.stl geometry. It works fine in paraview actually, but i'd like to extract such data points and thus need to be sure of what i'm looking at.
Also there is a data array at the end with 6 integers per line (value of 12 here)...I wonder what is the use for it?

Thanks a lot! 

[octree.zip](https://github.com/mhogg/pyoctree/files/3305011/octree.zip)

**Comment by mhogg** [comment]
As I thought, the 6 points are just two 3D points per line (you can tell from the total number of points, which is 19976, spread over half as many lines in the file).
The next integers are the cells (i.e. each line here is the list of points that form each cell. Note there are 8 points forming each cell)
The next integers (value of 12) correspond to the element types. Element type 12 is the 8 noded vtk_hexahedron.

**Comment by oliverstefanov** [comment]
Ok thanks a lot for your feedback. For cells connectivity it's the same deal I suppose, 6 integers per line but it really is 8 consecutive ints that form a cell. I'm surprised it doesn't disturb paraview. 

Also I just realized there is also an "offsets" data array with about 6 integers per line, for a total of 2497 elements, just like the number of cells. Is it used to designate the reference point for the vtk elements (just guessing)?

**Comment by mhogg** [comment]
This doesn't worry Paraview because it knows what each cell type is and therefore how many points it should read to form each cell. This is also where the offset is used. That is, if you look at the offset values they are 8, 16, 24, 32, 40, 48, 56 etc. This tells paraview that the starting point for the first cell is 0, for the second cell is 8, for the third cell is 16 etc.

The best document on vtk file formats that I have found (although several years old) is:
[https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf](https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf)

**Comment by oliverstefanov** [comment]
Alright makes sense, thank you very much for this information

**Comment by mhogg** [comment]
No problem
